### ISSUE TITLE
Outgoing ssl cert connections should use certificate chain

### ISSUE THREAD

**Issue by hnnesv** [jembi/openhim-core-js#615] opened 2016-02-03 11:40 UTC
Currently 'in-chain' certificate lookups are only [supported on incoming connections](https://github.com/jembi/openhim-core-js/blob/master/src/middleware/tlsAuthentication.coffee#L74). This method should also be supported (if enabled in config) on outgoing connections to servers.

**Comment by rcrichton** [comment] 2016-02-04 11:49
Duplicate of #559

**Closed by rcrichton** 2016-02-04 11:49 UTC
Labels: enhancement
